# LABVIEW2LCIOConfig.cmake.in
#
# cmake config file for LABVIEW2LCIO
#  LABVIEW2LCIO_INCLUDE_DIRS  - the LABVIEW2LCIO include directory
#  LABVIEW2LCIO_LIBRARIES     - The libraries needed to use LABVIEW2LCIO
#  LABVIEW2LCIO_DEFINITIONS   - the compile time definitions


#fixme: not true if INCLUDE_INSTALL_DIR is absolute path
SET( @PROJECT_NAME@_INCLUDE_DIRS "@FULL_INCLUDE_INSTALL_DIR@" )
SET( @PROJECT_NAME@_LIBRARIES    "@FULL_LIB_INSTALL_DIR@/@FULL_LIBRARY_NAME@" )

SET( @PROJECT_NAME@_DEFINITIONS @RECOSIPM_EXPORT_DEFINITIONS@ )

SET( @PROJECT_NAME@_ROOT_DIR "@CMAKE_INSTALL_PREFIX@" )

SET( @PROJECT_NAME@_MAJOR_VERSION "@RECOSIPM_MAJOR_VERSION@" )
SET( @PROJECT_NAME@_MINOR_VERSION "@RECOSIPM_MINOR_VERSION@" )
SET( @PROJECT_NAME@_PATH_LEVEL    "@RECOSIPM_PATCH_LEVEL@"    )


SET( @PROJECT_NAME@_FOUND TRUE )

